#!/usr/bin/python3
from sys import argv

list = []
second = 0
with open(argv[1]) as file:
    for value in file:
        number = int(value)
        print("{:d}=".format(number), end="")
        for i in range(number - 1, 0, -1):
            if number % i == 0:
                for first in range(1, i + 1, 1):
                    if i % first == 0:
                        list.append(first)
                    else:
                        continue
                if list[0] == 1 and list[1] == i:
                    second = number / i
                    print("{:d}*{:.0f}".format(i, second))
                    break
            else:
                continue
